# Generated by Django 4.2 on 2023-05-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_desc',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
