# Generated by Django 4.2 on 2023-05-02 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0002_event_event_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='username',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
